"""Generate readable measurement tables and additional geometry diagnostics."""
import csv
import itertools
import json
from collections import defaultdict
import numpy as np
import cv2
from run_audit import OUT, stats, write_csv, contains, SOURCE_REGION_SIZES, W, H


def read(name):
    with (OUT/name).open(encoding='utf-8',newline='') as f:
        return list(csv.DictReader(f))


def table(headers, rows):
    return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+
                     ['| '+' | '.join(map(str,row))+' |' for row in rows])+'\n\n'


def main():
    contact=cv2.imread(str(OUT/'figures/sequence_contact.png'))
    for i in range(5):
        cv2.imwrite(str(OUT/f'figures/sequence_strip_{i+1}.png'),contact[i*240:(i+1)*240],[cv2.IMWRITE_PNG_COMPRESSION,9])
    annotations=read('annotation_metrics.csv')
    for r in annotations:
        for k in r:
            if k!='class' and not k.endswith('bucket'): r[k]=float(r[k])
    classes=sorted({r['class'] for r in annotations})
    grouped={c:sorted([r for r in annotations if r['class']==c],key=lambda r:r['frame']) for c in classes}
    temporal=read('temporal_metrics.csv'); motion=read('motion_metrics.csv')
    stale=read('stale_summary.csv'); survival=read('survival_horizons.csv')
    pairs=read('camera_pair_summary.csv'); centered=read('camera_centered.csv')
    summary=json.loads((OUT/'scene_audit.json').read_text())
    out=['# Helsinki measurement appendix\n\nGenerated by `summarize_audit.py`. All results are MEASURED or deterministic DERIVED geometry. Counts are observations, not independent samples.\n\n']
    out.append('## Inventory and visibility\n\n')
    out.append(table(['Class','Frames','N','N/3 s','Span s','Entry evidence','Exit evidence'],
        [[r['class'],r['first_frame']+'-'+r['last_frame'],r['visible_frames'],f"{float(r['sampled_duration_s']):.2f}",f"{float(r['first_last_span_s']):.2f}",r['entry'],r['exit']] for r in temporal]))
    out.append('## Source and apparent scale\n\nWidth x height below are separate medians, not a synthetic observed box. Ranges are short-side minima-maxima. Boundary boxes are included and flagged in the raw data.\n\n')
    out.append(table(['Class','Source median W x H','L0 median W x H','L1 median W x H','L2 short range','L0 short range','Boundary/N'],
        [[c,f"{np.median([r['width'] for r in rr]):g} x {np.median([r['height'] for r in rr]):g}",
          f"{np.median([r['L0_width'] for r in rr]):g} x {np.median([r['L0_height'] for r in rr]):g}",
          f"{np.median([r['L1_width'] for r in rr]):g} x {np.median([r['L1_height'] for r in rr]):g}",
          f"{min(r['L2_short'] for r in rr):g}-{max(r['L2_short'] for r in rr):g}",
          f"{min(r['L0_short'] for r in rr):g}-{max(r['L0_short'] for r in rr):g}",
          f"{sum(int(r['boundary_touch']) for r in rr)}/{len(rr)}"] for c,rr in grouped.items()]))
    out.append(table(['Level','<4','4-<8','8-<16','16-32','>32'],
        [[l]+[next(r['count'] for r in read('scale_buckets.csv') if r['class']=='ALL' and r['level']==str(l) and r['bucket']==b) for b in ['<4','4-<8','8-<16','16-32','>32']] for l in range(3)]))
    out.append('Full per-class distributions, percentiles and exact class/frame scale buckets are in `class_summary.csv` and `scale_buckets.csv`.\n\n')
    out.append('## Motion\n\n')
    acceleration=[]
    for c,rr in grouped.items():
        for a,b,d in zip(rr,rr[1:],rr[2:]):
            if d['frame']-a['frame']!=2: continue
            ax=d['cx']-2*b['cx']+a['cx']; ay=d['cy']-2*b['cy']+a['cy']
            acceleration.append(dict(**{'class':c},frame=int(b['frame']),ax=ax,ay=ay,
                second_difference_px= float(np.hypot(ax,ay)),interior=not any(r['boundary_touch'] for r in [a,b,d])))
    write_csv('motion_second_differences.csv',acceleration)
    out.append(table(['Class','Pairs','Speed px/frame median [min,max]','Median dx,dy','Median area ratio','Median center 2nd difference px'],
        [[c,len(mm:=[r for r in motion if r['class']==c]),
          f"{np.median(v:=[float(r['displacement']) for r in mm]):.1f} [{min(v):.1f},{max(v):.1f}]",
          f"{np.median([float(r['dx']) for r in mm]):.1f}, {np.median([float(r['dy']) for r in mm]):.1f}",
          f"{np.median([float(r['area_ratio']) for r in mm]):.3f}",
          f"{np.median(aa):.1f}" if (aa:=[r['second_difference_px'] for r in acceleration if r['class']==c]) else 'n/a (2 frames)'] for c in classes]))
    out.append('Multiply pixels/frame by 3 for pixels/second. Second difference measures changes in image velocity; boundary clipping can move box centers independently of object centers.\n\n')
    out.append('## Future IoU on identical two-frame-history cohorts\n\nEach entry is valid/eligible (IoU >= 0.50), hold / velocity. This is localization with perfect initial boxes, not scored AP.\n\n')
    def val(c,h,m):
        match=[r for r in stale if r['class']==c and r['horizon']==str(h) and r['method']==m and r['cohort']=='paired_history']
        return (match[0]['valid_count']+'/'+match[0]['count']) if match else '-'
    out.append(table(['Class']+[f'h={h}' for h in [1,2,3,4,5,6,9,12]],
        [[c]+[val(c,h,'hold')+' / '+val(c,h,'velocity') for h in [1,2,3,4,5,6,9,12]] for c in ['ALL']+classes]))
    out.append('## Consecutive stale-valid prefixes\n\nAll eligible origins per method. Prefix zero means immediate failure. Maxima can be lower bounds if follow-up ends before failure. These cohorts differ; use the paired horizon table above for direct method comparison.\n\n')
    out.append(table(['Class','Hold median / max frames','Hold censored / N','Velocity median / max frames','Velocity censored / N'],
        [[c]+list(itertools.chain.from_iterable((
            [f"{np.median([int(r['valid_prefix_frames']) for r in ss]):g} / {max(int(r['valid_prefix_frames']) for r in ss)}",f"{sum(r['right_censored']=='True' for r in ss)}/{len(ss)}"] if (ss:=[r for r in survival if r['class']==c and r['method']==m]) else ['n/a','0/0']) for m in ['hold','velocity'])) for c in classes]))
    out.append('## Centered-camera geometry\n\nFull-box retention, excluding the target itself. Crop centers are rounded and clamped; results describe geometry, not a chosen policy or legal transition from every prior state.\n\n')
    out.append(table(['Class','L1 median other [min,max]','L1 isolated / N','L2 median other [min,max]','L2 isolated / N'],
        [[c]+list(itertools.chain.from_iterable([f"{np.median(v):g} [{min(v)},{max(v)}]",f"{sum(x==0 for x in v)}/{len(v)}"] for l in [1,2] for v in [[int(r['other_full_count']) for r in centered if r['target']==c and r['level']==str(l)]])) for c in classes]))
    out.append('### Co-visible pairs that fit L2 at least once\n\nAll pairs, distances and L1 fit counts (including those never fitting L2) are in `camera_pair_summary.csv`.\n\n')
    out.append(table(['Class A','Class B','Co-visible','Fits L1','Fits L2','Median separation px'],
        [[r['class_a'],r['class_b'],r['co_visible_frames'],r['fits_L1'],r['fits_L2'],f"{float(r['median_center_distance']):.0f}"] for r in pairs if int(r['fits_L2'])>0]))
    maxima=[]
    for f in range(25):
        rr=[r for r in annotations if r['frame']==f]
        for l in [1,2]:
            w,h=SOURCE_REGION_SIZES[l]
            # Full containment changes only at box edges or source boundaries.
            xs=sorted({0,W-w}|{int(np.clip(x,0,W-w)) for r in rr for x in [r['x1'],r['x2']-w]})
            ys=sorted({0,H-h}|{int(np.clip(y,0,H-h)) for r in rr for y in [r['y1'],r['y2']-h]})
            best=[]; bestxy=None
            for x,y in itertools.product(xs,ys):
                members=[r['class'] for r in rr if contains([x,y,x+w,y+h],[r[k] for k in ['x1','y1','x2','y2']])]
                if len(members)>len(best): best=members; bestxy=(x,y)
            maxima.append(dict(frame=f,level=l,max_full_count=len(best),total_objects=len(rr),
                x1=bestxy[0],y1=bestxy[1],classes=';'.join(best)))
    write_csv('camera_max_coverage.csv',maxima)
    out.append('### Maximum simultaneous complete boxes in any static crop\n\nAn exact sweep of containment boundary positions; one maximizing class set is saved per frame in `camera_max_coverage.csv`.\n\n')
    out.append(table(['Level','Max-count range','Median max count','Median covered fraction'],
        [[l,f"{min(r['max_full_count'] for r in ss)}-{max(r['max_full_count'] for r in ss)}",f"{np.median([r['max_full_count'] for r in ss]):g}",f"{np.median([r['max_full_count']/r['total_objects'] for r in ss]):.2f}"] for l in [1,2] for ss in [[r for r in maxima if r['level']==l]]]))
    (OUT/'MEASUREMENTS.md').write_text(''.join(out),encoding='utf-8')
    print('Wrote MEASUREMENTS.md, motion_second_differences.csv, camera_max_coverage.csv')
    print(json.dumps(summary['camera'],indent=2))


if __name__=='__main__': main()
